### ISSUE TITLE
ETL job to migrate an organization from prod database to dev database

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-functions#7]
We need a function/job/command to incrementally transport the data in our prod database that belongs to a specified organization on Greenstand, and do some transform, then dump into our dev database.

The data need to be transported are:
* New planter under the org
* New capture belongs to the org
* New species created by these tree.
* New token minted on capture above.
* Wallet that occupy token above.

Language, could by Python or Node.js.

**Comment by aayushgauba** [comment]
@dadiorchen I will work on this

**Comment by dadiorchen** [comment]
You are our hero!

**Comment by aayushgauba** [comment]
@dadiorchen so we are basically transforting filtered data from v1 of prod to v1 of dev?

**Comment by dadiorchen** [comment]
@aayushgauba this task is about to copy the data in prod and move to the dev db, after some cleanup work

**Comment by dadiorchen** [comment]
@aayushgauba I will close this one, let's do this in #8
